# server配置
server:
  port:8003

# spring配置
spring:

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yogovi_new?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: 285413

    hikari:
      # hikari连接池配置
      maxinum-pool-size: 50
      minimum-idle: 8