# server配置
server:
  port: 8765
  context-path: /test

# spring配置
spring:
  #引用外部文件
  profiles:
    active: activemq


  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: 285413


  #druid数据源配置
  druid:
      max-active: 5
      max-wait: 6000

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      mix-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 1000
    databse: 0

  #rabbitmq消息
  application:


#  mvc:
#    static-path-pattern: /index/**
  resources:
    static-locations: classpath:/index,/META-INF/resource

  #邮件配置
  mail:
    host: smtp.qq.com
    username: 1142925345@qq.com
    password: pmlqatcseworiiah
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true

#mybatis配置
  #配置实体类映射和mapper.xml文件路径
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath:mapper/*.xml

#日志配置
#logging:
  #config: classpath:logback.xml

